version: "3.0"
services:
 wordpress: 
    image: wordpress:latest
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: "abc123"
 mysql:
    image: mysql:5.7
    environment:
     MYSQL_DB_PASSWORD: "xyz123"
